plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

// Generated by go.attestra.aws.auth: deploy -export-android <file>.
val environmentFile = providers.gradleProperty("attestraConfigFile").orNull
val environmentSettings = java.util.Properties().apply {
    environmentFile?.let { path ->
        val config = rootProject.file(path)
        require(config.isFile) { "Attestra configuration file not found: $path" }
        config.reader(Charsets.UTF_8).use { load(it) }
    }
}
fun setting(name: String, fallback: String = ""): String =
    providers.gradleProperty(name).orNull ?: environmentSettings.getProperty(name) ?: fallback
fun quoted(value: String): String {
    require(value.none { it.isISOControl() }) { "Attestra properties must not contain control characters" }
    return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
if (environmentFile != null) {
    listOf("attestraEnvironment", "attestraApiBaseUrl", "attestraLinkHost", "attestraAwsRegion",
        "attestraCognitoUserPoolId", "attestraCognitoClientId", "attestraCaptureEnabled", "attestraCaptureDocumentType")
        .forEach { require(setting(it).isNotBlank()) { "Missing $it in Attestra environment configuration" } }
}
val authApiBaseUrl = setting("attestraApiBaseUrl")
val authLinkHost = setting("attestraLinkHost", "example.invalid")
val captureEnabled = setting("attestraCaptureEnabled", "false").toBooleanStrictOrNull()
    ?: error("attestraCaptureEnabled must be true or false")
require(authApiBaseUrl.isEmpty() || runCatching {
    val uri = java.net.URI(authApiBaseUrl)
    uri.scheme == "https" && !uri.host.isNullOrBlank() && uri.userInfo == null && uri.query == null && uri.fragment == null
}.getOrDefault(false)) { "attestraApiBaseUrl must be an HTTPS API URL" }
require(authLinkHost.matches(Regex("[A-Za-z0-9.-]+"))) { "attestraLinkHost must be a hostname" }

android {
    namespace = "com.apexfission.android.attestra.auth"
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId = "com.apexfission.android.attestra.auth"
        minSdk = 28
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        manifestPlaceholders["attestraLinkHost"] = authLinkHost

        buildConfigField("String", "AUTH_API_BASE_URL", "\"${authApiBaseUrl.replace("\\", "\\\\").replace("\"", "\\\"")}\"")
        buildConfigField("String", "AUTH_LINK_HOST", "\"$authLinkHost\"")
        buildConfigField("String", "ATTESTRA_ENVIRONMENT", quoted(setting("attestraEnvironment")))
        buildConfigField("String", "AWS_REGION", quoted(setting("attestraAwsRegion")))
        buildConfigField("String", "COGNITO_USER_POOL_ID", quoted(setting("attestraCognitoUserPoolId")))
        buildConfigField("String", "COGNITO_CLIENT_ID", quoted(setting("attestraCognitoClientId")))
        buildConfigField("boolean", "CAPTURE_ENABLED", captureEnabled.toString())
        buildConfigField("String", "CAPTURE_DOCUMENT_TYPE", quoted(setting("attestraCaptureDocumentType", "sample_card")))
    }

    buildTypes {
        release {
            optimization {
                enable = false
            }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
}

dependencies {
    implementation(project(":auth"))
    debugImplementation(project(":identity-mock"))
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.compose.material3)
    implementation("androidx.compose.material:material-icons-extended")
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    
    // Ktor client & Serialization
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.cio)
    implementation(libs.ktor.client.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.junit)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
    debugImplementation(libs.androidx.compose.ui.tooling)
}
